## Assertion that a code fragment throws a particular exception (self-test utility, Python 3)  
Originally published: 2008-06-14 05:56:53  
Last updated: 2010-07-20 13:15:49  
Author: Dmitry Dvoinikov  
  
The class presented in this recipe is useful when you are writing module self-tests and need to assert that a fragment of code throws a particular exception.